import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Kameron, Kadwa } from "next/font/google";
import { ViewTransition } from 'react'
import { Toaster } from "@/components/ui/sonner"
import { AppearanceSync } from "@/components/controllers/AppearanceSync";
import Script from "next/script";
import "../globals.css";
import { UIStoreProvider } from "@/store/ui/ui.provider";
import { AuthProvider } from "@/contexts/AuthContext";
import { getServerPreferences } from "@/lib/server/preferences";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kameron = Kameron({
  variable: "--font-kameron",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const kadwa = Kadwa({
  variable: "--font-kadwa",
  subsets: ["latin"],
  weight: "400",
});

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({ children, params }: LocaleLayoutProps) {
  const { locale } = await params;

  const messages = await getMessages();
  const prefs = await getServerPreferences();

  return (
    <html lang={locale} className={prefs.theme}>
      <body className={`${kameron.variable} ${kadwa.variable} antialiased h-screen transition-all duration-300`}>
        <div className="h-full max-w-[1920px] mx-auto py-6 sm:py-10 md:py-12 px-4 sm:px-6 md:px-8 lg:px-12">
          <Script
            src="//unpkg.com/react-scan/dist/auto.global.js"
            strategy="beforeInteractive"
          />
          <NextIntlClientProvider locale={locale} messages={messages}>
            <AuthProvider>
              <ViewTransition>
                <UIStoreProvider initialState={prefs}>
                  {children}
                  <Toaster />
                  <AppearanceSync />
                </UIStoreProvider>
              </ViewTransition>
            </AuthProvider>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
